services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_DATABASE: std_mng
      MYSQL_USER: manager_std
      MYSQL_PASSWORD: 123qwe
      MYSQL_ROOT_PASSWORD: root1234
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./BE/std-mng/src/main/resources/schema.sql:/docker-entrypoint-initdb.d/1_schema.sql
      - ./BE/std-mng/src/main/resources/data.sql:/docker-entrypoint-initdb.d/2_data.sql
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build: ./BE/std-mng
    container_name: backend
    ports:
      - "8080:8080"
    networks:
      - app-network
    depends_on:
      mysql:
        condition: service_healthy

  frontend:
    build: ./FE
    container_name: frontend
    ports:
      - "80:80"
    networks:
      - app-network
    depends_on:
      - backend

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge